version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: 'mysql:5.7'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
      - 'TZ=Asia/Seoul'
    ports:
      - '3306'
