spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      encoding: UTF-8

server:
  servlet:
    encoding:
      force-request: true
      force-response: true

logging:
  level:
    root: debug

jwt:
  secret-key: secret
  access-token-validity-in-millis: 600000
  refresh-token-validity-in-millis: 1209600000
